# Generated by Django 2.0.5 on 2018-10-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twipin', '0002_curtida'),
    ]

    operations = [
        migrations.AddField(
            model_name='twip',
            name='lat',
            field=models.FloatField(default=-27.368230173997716),
        ),
        migrations.AddField(
            model_name='twip',
            name='lng',
            field=models.FloatField(default=-53.40367164684574),
        ),
    ]
